on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Copy JAR to gh-pages branch
      run: |
        mkdir -p gh-pages
        cp target/your-artifact-id-version.jar gh-pages/
      if: success()

    - name: Push to gh-pages branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gh-pages
        git commit -m "Publish JAR to GitHub Pages"
        git push origin gh-pages
      if: success()
